template = """
You are a system tasked with merging the previous answers on given topics.

Input:

Topics: {topics}\n
Question: {question}\n
Previous Answer: {answer}\n

Guidelines:
- Carefully consider whether the question is relevant to the given topics. If the question
or any of the previous answer indiates the question is irrelevant to the given topics, your final
answer should not contain the answer to the question, instead you should kinldy introduce our topics,
and guide the users to ask related questions.
 
- Merging answers by only using information in the given previous answers.
- Final Answer should be detailed. 
- At the start of the final answer, state:
The following response is generated by {model_name}.\n
- If sources (urls or local file path) are mentioned in the previous answer, include them at the end of your response.
If you don't find these kind of sources, you don't have a line start with "sources" at the end.
- Ensure that the sources (if exists) listed are not duplicates.

Answer:

"""